using DevExpress.Persistent.Base;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Text.RegularExpressions;

namespace PowderCoatingWizard.Module.Services.AI
{
    /// <summary>
    /// Executes read-only SELECT statements generated by the internal DBChat tool.
    /// The executor fails closed and blocks data modification, DDL, multi-statement batches, and unsafe SQL tokens.
    /// </summary>
    public sealed class SafeSqlExecutor
    {
        private static readonly Regex UnsafeTokenRegex = new(
            @"\b(insert|update|delete|merge|drop|alter|truncate|create|exec|execute|grant|revoke|backup|restore|dbcc|xp_)\b",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private readonly string? _connectionString;
        private readonly int _commandTimeoutSeconds;

        public SafeSqlExecutor(string? connectionString, int commandTimeoutSeconds = 30)
        {
            _connectionString = SqlClientConnectionStringSanitizer.Sanitize(connectionString);
            _commandTimeoutSeconds = Math.Clamp(commandTimeoutSeconds, 5, 120);
        }

        public async Task<DataTable> ExecuteSafeSelectAsync(string sql, int maxRows, CancellationToken ct = default)
        {
            var safeSql = NormalizeAndValidate(sql);
            var limitedSql = ApplyTopLimit(safeSql, maxRows);

            var table = new DataTable("DatabaseInsight");
            if (string.IsNullOrWhiteSpace(_connectionString))
                return table;

            try
            {
                await using var connection = new SqlConnection(_connectionString);
                await connection.OpenAsync(ct);

                await using var command = connection.CreateCommand();
                command.CommandText = limitedSql;
                command.CommandTimeout = _commandTimeoutSeconds;

                await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SequentialAccess | CommandBehavior.SingleResult, ct);
                table.Load(reader);
                return table;
            }
            catch (Exception ex)
            {
                Tracing.Tracer.LogError(ex);
                throw;
            }
        }

        public static string NormalizeAndValidate(string sql)
        {
            if (string.IsNullOrWhiteSpace(sql))
                throw new InvalidOperationException("SQL is required.");

            var normalized = sql.Trim();
            if (normalized.StartsWith("```", StringComparison.Ordinal))
                normalized = StripCodeFence(normalized);

            normalized = normalized.Trim().TrimEnd(';').Trim();
            var withoutComments = RemoveComments(normalized);

            if (!withoutComments.StartsWith("select", StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("Only SELECT statements are allowed.");

            if (withoutComments.Contains(';'))
                throw new InvalidOperationException("Multiple SQL statements are not allowed.");

            if (UnsafeTokenRegex.IsMatch(withoutComments))
                throw new InvalidOperationException("The SQL statement contains a blocked command or token.");

            return normalized;
        }

        private static string ApplyTopLimit(string sql, int maxRows)
        {
            maxRows = maxRows > 0 ? maxRows : 50;
            var trimmed = sql.Trim();

            if (Regex.IsMatch(trimmed, @"^select\s+(distinct\s+)?top\s*\(", RegexOptions.IgnoreCase) ||
                Regex.IsMatch(trimmed, @"^select\s+(distinct\s+)?top\s+\d+", RegexOptions.IgnoreCase) ||
                Regex.IsMatch(trimmed, @"\boffset\s+\d+\s+rows\b", RegexOptions.IgnoreCase))
            {
                return trimmed;
            }

            var distinctMatch = Regex.Match(trimmed, @"^select\s+distinct\s+", RegexOptions.IgnoreCase);
            if (distinctMatch.Success)
                return "SELECT DISTINCT TOP (" + maxRows + ") " + trimmed[distinctMatch.Length..];

            var selectMatch = Regex.Match(trimmed, @"^select\s+", RegexOptions.IgnoreCase);
            if (selectMatch.Success)
                return "SELECT TOP (" + maxRows + ") " + trimmed[selectMatch.Length..];

            return trimmed;
        }

        private static string StripCodeFence(string text)
        {
            var lines = text.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries)
                .Where(line => !line.Trim().StartsWith("```", StringComparison.Ordinal))
                .ToArray();
            return string.Join(Environment.NewLine, lines);
        }

        private static string RemoveComments(string sql)
        {
            var noBlockComments = Regex.Replace(sql, @"/\*.*?\*/", string.Empty, RegexOptions.Singleline);
            return Regex.Replace(noBlockComments, @"--.*?$", string.Empty, RegexOptions.Multiline);
        }
    }
}
