using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.MultiTenancy;
using DevExpress.ExpressApp.Security;
using DevExpress.ExpressApp.Security.Strategy;
using DevExpress.ExpressApp.SystemModule;
using DevExpress.ExpressApp.Updating;
using DevExpress.ExpressApp.Xpo;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.BaseImpl.MultiTenancy;
using DevExpress.Persistent.BaseImpl.PermissionPolicy;
using DevExpress.Xpo;
using Microsoft.Extensions.DependencyInjection;
using PowderCoatingWizard.Module.BusinessObjects;
using PowderCoatingWizard.Module.BusinessObjects.AI;

namespace PowderCoatingWizard.Module.DatabaseUpdate
{
    // For more typical usage scenarios, be sure to check out https://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.Updating.ModuleUpdater
    public class Updater : ModuleUpdater
    {
        public Updater(IObjectSpace objectSpace, Version currentDBVersion) :
            base(objectSpace, currentDBVersion)
        {
        }
        public override void UpdateDatabaseAfterUpdateSchema()
        {
            base.UpdateDatabaseAfterUpdateSchema();
            //string name = "MyName";
            //DomainObject1 theObject = ObjectSpace.FirstOrDefault<DomainObject1>(u => u.Name == name);
            //if(theObject == null) {
            //    theObject = ObjectSpace.CreateObject<DomainObject1>();
            //    theObject.Name = name;
            //}
            if (!ObjectSpace.CanInstantiate(typeof(ApplicationUser)))
            {
                return;
            }

            // Ensure exactly one AIProviderSettings singleton exists.
            // Only seed inside a tenant database, not in the empty host database.
            if (TenantId != null && ObjectSpace.GetObjectsCount(typeof(AIProviderSettings), null) == 0)
            {
                var settings = ObjectSpace.CreateObject<AIProviderSettings>();
                settings.DisplayName = "Default AI Provider";
                settings.IsEnabled = true;
            }

            SeedParameterUnits();

#if !RELEASE
            if (TenantName == null)
            {
                _ = CreateTenant("company1.com", "PowderCoatingWizard_company1");
                _ = CreateTenant("company2.com", "PowderCoatingWizard_company2");
                ObjectSpace.CommitChanges();
            }
#endif

            // The code below creates users and roles for testing purposes only.
            // In production code, you can create users and assign roles to them automatically, as described in the following help topic:
            // https://docs.devexpress.com/eXpressAppFramework/119064/data-security-and-safety/security-system/authentication
#if !RELEASE
            // If a role doesn't exist in the database, create this role
            var adminRole = CreateAdminRole();

            UserManager userManager = ObjectSpace.ServiceProvider.GetRequiredService<UserManager>();

            if (TenantName != null)
            {
                var defaultRole = CreateDefaultRole();

                string userName = $"User@{TenantName}";
                // If a user named 'userName' doesn't exist in the database, create this user
                if (userManager.FindUserByName<ApplicationUser>(ObjectSpace, userName) == null)
                {
                    // Set a password if the standard authentication type is used
                    string EmptyPassword = "";
                    _ = userManager.CreateUser<ApplicationUser>(ObjectSpace, userName, EmptyPassword, (user) =>
                    {
                        // Add the Users role to the user
                        user.Roles.Add(defaultRole);
                    });
                }
            }

            string adminUserName = TenantName != null ? $"Admin@{TenantName}" : "Admin";
            if (userManager.FindUserByName<ApplicationUser>(ObjectSpace, adminUserName) == null)
            {
                // Set a password if the standard authentication type is used
                string EmptyPassword = "";
                _ = userManager.CreateUser<ApplicationUser>(ObjectSpace, adminUserName, EmptyPassword, (user) =>
                {
                    // Add the Administrators role to the user
                    user.Roles.Add(adminRole);
                });
            }

            ObjectSpace.CommitChanges(); //This line persists created object(s).
            if (TenantName != null)
            {
                _ = CreateDefaultRole();
            }

            if (TenantName == null && OperatingSystem.IsWindows())
            {
                string autogeneratedAdminUserName = System.Security.Principal.WindowsIdentity.GetCurrent().Name;
                if (userManager.FindUserByName<ApplicationUser>(ObjectSpace, autogeneratedAdminUserName) == null)
                {
                    // Set a password if the standard authentication type is used
                    string EmptyPassword = "";
                    _ = userManager.CreateUser<ApplicationUser>(ObjectSpace, autogeneratedAdminUserName, EmptyPassword, (user) =>
                    {
                        // Add the Administrators role to the user
                        user.Roles.Add(adminRole);

                        userManager.AddLogin(user, SecurityDefaults.WindowsAuthentication, autogeneratedAdminUserName);
                    });
                }
            }

            ObjectSpace.CommitChanges(); //This line persists created object(s).
#endif
        }
        public override void UpdateDatabaseBeforeUpdateSchema()
        {
            base.UpdateDatabaseBeforeUpdateSchema();
            //if(CurrentDBVersion < new Version("1.1.0.0") && CurrentDBVersion > new Version("0.0.0.0")) {
            //    RenameColumn("DomainObject1Table", "OldColumnName", "NewColumnName");
            //}
        }
        Tenant CreateTenant(string tenantName, string databaseName)
        {
            var tenant = ObjectSpace.FirstOrDefault<Tenant>(t => t.Name == tenantName);
            if (tenant == null)
            {
                tenant = ObjectSpace.CreateObject<Tenant>();
                tenant.Name = tenantName;
                tenant.ConnectionString = $"Data Source=(localdb)\\mssqllocaldb;Integrated Security=SSPI;Pooling=false;Initial Catalog={databaseName}";
            }
            return tenant;
        }
        PermissionPolicyRole CreateAdminRole()
        {
            PermissionPolicyRole adminRole = ObjectSpace.FirstOrDefault<PermissionPolicyRole>(r => r.Name == "Administrators");
            if (adminRole == null)
            {
                adminRole = ObjectSpace.CreateObject<PermissionPolicyRole>();
                adminRole.Name = "Administrators";
                adminRole.IsAdministrative = true;
            }
            return adminRole;
        }
        PermissionPolicyRole CreateDefaultRole()
        {
            PermissionPolicyRole defaultRole = ObjectSpace.FirstOrDefault<PermissionPolicyRole>(role => role.Name == "Default");
            if (defaultRole == null)
            {
                defaultRole = ObjectSpace.CreateObject<PermissionPolicyRole>();
                defaultRole.Name = "Default";

                defaultRole.AddObjectPermissionFromLambda<ApplicationUser>(SecurityOperations.Read, cm => cm.Oid == (Guid)CurrentUserIdOperator.CurrentUserId(), SecurityPermissionState.Allow);
                defaultRole.AddNavigationPermission(@"Application/NavigationItems/Items/Default/Items/MyDetails", SecurityPermissionState.Allow);
                defaultRole.AddMemberPermissionFromLambda<ApplicationUser>(SecurityOperations.Write, "ChangePasswordOnFirstLogon", cm => cm.Oid == (Guid)CurrentUserIdOperator.CurrentUserId(), SecurityPermissionState.Allow);
                defaultRole.AddMemberPermissionFromLambda<ApplicationUser>(SecurityOperations.Write, "StoredPassword", cm => cm.Oid == (Guid)CurrentUserIdOperator.CurrentUserId(), SecurityPermissionState.Allow);
                defaultRole.AddTypePermissionsRecursively<PermissionPolicyRole>(SecurityOperations.Read, SecurityPermissionState.Deny);
                defaultRole.AddObjectPermission<ModelDifference>(SecurityOperations.ReadWriteAccess, "UserId = ToStr(CurrentUserId())", SecurityPermissionState.Allow);
                defaultRole.AddObjectPermission<ModelDifferenceAspect>(SecurityOperations.ReadWriteAccess, "Owner.UserId = ToStr(CurrentUserId())", SecurityPermissionState.Allow);
                defaultRole.AddTypePermissionsRecursively<ModelDifference>(SecurityOperations.Create, SecurityPermissionState.Allow);
                defaultRole.AddTypePermissionsRecursively<ModelDifferenceAspect>(SecurityOperations.Create, SecurityPermissionState.Allow);
                defaultRole.AddTypePermission<AuditDataItemPersistent>(SecurityOperations.Read, SecurityPermissionState.Deny);
                defaultRole.AddObjectPermissionFromLambda<AuditDataItemPersistent>(SecurityOperations.Read, a => a.UserId == CurrentUserIdOperator.CurrentUserId().ToString(), SecurityPermissionState.Allow);
                defaultRole.AddTypePermission<AuditedObjectWeakReference>(SecurityOperations.Read, SecurityPermissionState.Allow);
            }
            return defaultRole;
        }

        void SeedParameterUnits()
        {
            if (!ObjectSpace.CanInstantiate(typeof(ParameterUnit))) return;

            void Ensure(string name, string symbol, string description = "")
            {
                if (ObjectSpace.FirstOrDefault<ParameterUnit>(u => u.Symbol == symbol) != null) return;
                var u = ObjectSpace.CreateObject<ParameterUnit>();
                u.Name = name;
                u.Symbol = symbol;
                u.Description = description;
            }

            Ensure("pH unit",                          "pH",       "Acidity/alkalinity scale for conversion bath.");
            Ensure("Microsiemens per centimetre",       "µS/cm",    "Electrical conductivity of the bath solution.");
            Ensure("Grams per litre",                  "g/L",      "Concentration of chemical additive.");
            Ensure("Degrees Celsius",                  "°C",       "Bath temperature.");
            Ensure("Seconds",                          "sec",      "Contact time of the part with the bath.");
            Ensure("Milligrams per square metre",      "mg/m²",    "Thickness of the conversion layer (Ti layer).");
            Ensure("Points",                           "pts",      "Impurity level score.");
            Ensure("Milligrams O₂ per litre",         "mg/L O₂",  "Chemical oxygen demand (COD).");
            Ensure("Litres per square metre",          "L/m²",     "Dosing rate — AM coefficient.");
            Ensure("Litres per 100 kg",                "L/100kg",  "Chemical consumption per 100 kg of aluminium processed.");
            Ensure("Litres",                           "L",        "Volume unit for top-up calculations.");
            Ensure("Square metres",                    "m²",       "Surface area processed through the bath.");
            Ensure("Kilograms",                        "kg",       "Weight of aluminium processed.");

            ObjectSpace.CommitChanges();
        }

        Guid? TenantId
        {
            get
            {
                return ObjectSpace.ServiceProvider.GetRequiredService<ITenantProvider>().TenantId;
            }
        }
        string TenantName
        {
            get
            {
                return ObjectSpace.ServiceProvider.GetRequiredService<ITenantProvider>().TenantName;
            }
        }
    }
}
